<?php


namespace serviceBundle\Repository;
use MyBundle\Entity\Service;
use Doctrine\ORM\Query;
/**
 * serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s
        FROM MyBundle:Service s
        WHERE s.description LIKE :str'

            )->setParameter('str', '%'.$str.'%')->getResult();
    }
    public function findCommande($user)
    {
        $query=$this->getEntityManager()
            ->createQuery("select s from MyBundle:Service s WHERE s.idUser='$user'");
        return $query->getResult();
    }
    public function findService(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c.ids,c.description,c.date,u.ida,u.typea
                            FROM MyBundle:attestation u JOIN MyBundle:Service c WITH u.ida = c.ida
                            ");
        if(count($query->getArrayResult()) > 0) return $query->getResult();
        return null;
    }
}
