<?php

namespace MyBundle\Repository;

/**
 * attestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attestationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findattestation(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u.langue,u.typea
                            FROM MyBundle:attestation u 
                            ");
        if(count($query->getArrayResult()) > 0) return $query->getResult();
        return null;
    }
}
