<?php

namespace MyBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTri()
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM MyBundle:Evenement
                p ORDER BY p.date ASC"
                )
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }


}