<?php

namespace MyBundle\Repository;

/**
 * ExamCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
