<?php

namespace MyBundle\Repository;

/**
 * FormationsOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationsOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
