<?php

namespace MyBundle\Repository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTri()
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM MyBundle:Offre
                p ORDER BY p.prix ASC"
                )
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }


    public function findByNom($nom)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM MyBundle:Offre
                p where p.description like :nom"
                )
                ->setParameter('nom', '%'.$nom.'%')
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }
}