<?php

namespace MyBundle\Repository;

/**
 * StudentExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentExamRepository extends \Doctrine\ORM\EntityRepository
{
}
